### ISSUE TITLE
docs.plasmapy.org

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/plasmapy.github.io#12]
https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/%2415156890863374dLJNp:matrix.org it's all  here

**Comment by namurphy** [comment]
I just logged in to register.com and set it so that [docs.plasmapy.org](http://docs.plasmapy.org) forwards to our Read the Docs page.  I'm pretty unfamiliar with how to set things like this up, but it would be great if we could have it so that the page showed up as docs.plasmapy.org instead of being forwarded.

**Comment by StanczakDominik** [comment]
I think I saw something related to that in RTD setting, either on the website or in conf.py. I'll look at that in the evening.

**Comment by StanczakDominik** [comment]
@namurphy can you look at it now? I may have solved it.

**Comment by namurphy** [comment]
I went to [http://docs.plasmapy.org/](http://docs.plasmapy.org/) and what we have on read the docs showed up as [http://docs.plasmapy.org/en/latest/](http://docs.plasmapy.org/en/latest/), so it does look like it's working.  Thank you!
